### ISSUE TITLE
Initdb

### ISSUE THREAD

**Issue by nhubert** [puckel/docker-airflow#107]
Hello,

I don't understand why the webserver is initiliazing the db everytime it's launched. It should be a one time thing. When the container crash it resets the db.

How can i avoid that ?

Thank you

**Comment by hporter** [comment]
How are you hosting your database, locally in Docker? I am deploying this image to Google Container Engine with a separate postgres database on Google Cloud SQL and it works well.

**Comment by mhousley** [comment]
Container storage is ephemeral; by default, you will lose your database every time you restart the cluster. You can address this by mounting a persistent volume. For example, modify your compose file like this:
```
postgres:
          image: postgres:9.6
          environment:
              - POSTGRES_USER=airflow
              - POSTGRES_PASSWORD=airflow
              - POSTGRES_DB=airflow
              - PGDATA=/var/lib/postgresql/data/pgdata
          volumes:
              - ./pgdata:/var/lib/postgresql/data/pgdata
```
The `PGDATA` variable specifies the database storage path in the container; we then specify a volume mounting this path on the host machine. See also https://hub.docker.com/_/postgres/
