### ISSUE TITLE
[Question] - Airflow environment variable -> airflow.cfg

### ISSUE THREAD

**Issue by emirot** [puckel/docker-airflow#109]
Have you been able to add environment variables as describe here :  https://airflow.incubator.apache.org/configuration.html#setting-configuration-options ?

When I add : 

```AIRFLOW__CORE__SQL_ALCHEMY_CONN``` in the docker-compose file it gets replaced inside the airflow.cfg 

Example : 
```
  webserver:
        image: puckel/docker-airflow:1.8.1-1
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=my_test
``` 
but 
```
  webserver:
        image: puckel/docker-airflow:1.8.1-1
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - AIRFLOW__SMTP__STMP_HOST=my_smtp_host
``` 
the environment variable AIRFLOW__SMTP__STMP_HOST is inside the container but won't get replaced inside the airflow.cfg

I know that one way could be to replace the variable  inside airflow.cfg directly but I wanted to use these environment variables.
 Do you think it's because you copy the file instead of letting airflow creating it ? 
Thanks for your help.

Best,

Nolan
