### ISSUE TITLE
Use requirements.txt file.

### ISSUE THREAD

**Issue by ttelfer** [puckel/docker-airflow#111]
It may be worth adding a requirements.txt file, which would help clean up the Dockerfile.

**Comment by sdikby** [comment]
you can specify one [here](here https://github.com/puckel/docker-airflow/blob/d062774985037a7c01e2db306981f76321f72f1e/script/entrypoint.sh#L24)

**Comment by y2k-shubham** [comment]
For the `python`-*infants* who dunno how to pull off that `requirements.txt` thing, here's how i did it:

- Create a file `requirements.txt` in root folder of project and list-out your dependencies as shown [here](https://stackoverflow.com/q/7225900/3679900)

- If you're using `Dockerfile`, place following line in it like [this](https://github.com/puckel/docker-airflow/blob/1.10.0-1/Dockerfile#L77)
`COPY requirements.txt /requirements.txt`

- If your'e using `docker-compose-XXX`, place following line in it like [this](https://github.com/puckel/docker-airflow/blob/1.10.0-1/docker-compose-CeleryExecutor.yml#L63) for mounting volume (should be done for `scheduler` as well as `worker` in `CeleryExecutor`)
`- ./requirements.txt:/requirements.txt`

**Comment by Wapiti08** [comment]
> For the `python`-_infants_ who dunno how to pull off that `requirements.txt` thing, here's how i did it:
> 
> * Create a file `requirements.txt` in root folder of project and list-out your dependencies as shown [here](https://stackoverflow.com/q/7225900/3679900)
> * If you're using `Dockerfile`, place following line in it like [this](https://github.com/puckel/docker-airflow/blob/1.10.0-1/Dockerfile#L77)
>   `COPY requirements.txt /requirements.txt`
> * If your'e using `docker-compose-XXX`, place following line in it like [this](https://github.com/puckel/docker-airflow/blob/1.10.0-1/docker-compose-CeleryExecutor.yml#L63) for mounting volume (should be done for `scheduler` as well as `worker` in `CeleryExecutor`)
>   `- ./requirements.txt:/requirements.txt`

I tried both of your methods.
This is my code for Dockerfile:
```
osboxes@osboxes:~/docker_airflow$ vim Dockerfile 

FROM puckel/docker-airflow:1.10.6
RUN pip install --user psycopg2-binary -i https://pypi.tuna.tsinghua.edu.cn/simple/
ENV AIRFLOW_HOME=/usr/local/airflow
ARG Client
ARG Types
COPY ./airflow_home/airflow.cfg /usr/local/airflow/airflow.cfg
COPY ./airflow_home/__init__.py /usr/local/airflow/__init__.py
# CMD python3 .airflow_home/__init__.py -C $Client -T $Types
RUN python3 $PWD/__init__.py -C $Client -T $Types
```
Here is part of my docker-compose.yml:
```
# comment initdb after you will have use it at first run
    # set the client and processed log types here
    initdb:
        build:
            context: .
            args:
                 Client: Local
                 Types: Windows
        volumes:
            - './requirements.txt:/requirements.txt'
        entrypoint: airflow initdb
        depends_on:
            - postgres

    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
        volumes:
            - './airflow_home/dags:/usr/local/airflow/dags'
            - './airflow_home/plugins:/usr/local/airflow/plugins'
        ports:
            - "8080:8080"
        entrypoint: 'airflow webserver'
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
```
I need to **compose up initdb** first. But I would get the error 
```
joblib library doesn't exist
```
I put joblib in requirements.txt. But the **pip install -r xxx** did not run before the final CMD in dockerfile. I can not find the solution to solve it. Hope to get your suggestion on that. Thanks
