### ISSUE TITLE
Example utilizing RDS or other external Postgres instance?

### ISSUE THREAD

**Issue by maxcountryman** [puckel/docker-airflow#149]
Hi, I'm wondering if there's some example of using this configuration with an RDS instance of Postgres? It seems that standing up Postgres inside of the Docker Compose configuration means that there is possibly no persistence between deployments. As such it seems a better option might be to point to Postgres running in a different context.

**Comment by chribsen** [comment]
You can connect to any externally hosted PostgreSQL database by injecting a connection string into the Airflow containers using the `AIRFLOW__CORE__SQL_ALCHEMY_CONN` environment variable.

**Comment by roirodriguez** [comment]
@chribsen: I'm trying exactly this to connect to mysql instead of postgres and it's not working. My compose file

```
version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
    volumes:
      - mysqlairflowdata:/var/lib/mysql
  airflow:
    image: puckel/docker-airflow:1.8.2
    depends_on:
      - mysql
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql://airflow:airflow@mysql:3306/airflow
    ports:
      - "8080:8080"
    volumes:
      - ./airflow-dags:/usr/local/airflow/dags
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  mysqlairflowdata:
```

If i run this:

```bash
$ docker-compose up -d
$ docker-compose logs -f airflow
airflow_1  | Tue Feb 20 14:09:38 UTC 2018 - waiting for postgres:5432... 1/20
```

Anybody have some working sample with config env variables passed through docker-compose.yml? I can't make this to work.
