### ISSUE TITLE
airflow CLI commands using `docker exec -it` ignore the config in compose files

### ISSUE THREAD

**Issue by cmardiros** [puckel/docker-airflow#157]
I have pulled this repo and changed postgres details in `docker-compose-LocalExecutor.yml` to the following (nothing else changed). Note that load examples is set to False and executor is set to LocalExecutor

```
version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=w63kIwod7gae
            - POSTGRES_PASSWORD=OioE9068995S
            - POSTGRES_DB=airdb

    webserver:
        image: puckel/docker-airflow:1.9.0
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_USER=w63kIwod7gae
            - POSTGRES_PASSWORD=OioE9068995S
            - POSTGRES_DB=airdb
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
```

I then did:
```
docker-compose -f docker-compose-LocalExecutor.yml up --build
```

This starts the container correctly and I can see in the console that the configuration was picked up correctly:

```
webserver_1  | [2018-02-09 17:55:17,519] {{__init__.py:45}} INFO - Using executor LocalExecutor
webserver_1  | DB: postgresql+psycopg2://w63kIwod7gae:***@postgres:5432/airdb
```

I can access the admin ok and I can trigger tutorial dag ok.

Now, I then log into the container interactively:
```
docker exec -it $(docker-compose -f docker-compose-LocalExecutor.yml ps -q webserver) bash
```

If I do:
```
airflow connections
# brings up Using executor CeleryExecutor
```

```
airflow trigger_dag example_python_operator
# returns FATAL:  password authentication failed for user "airflow" (note that user defined in compose is w63kIwod7gae)
```

```
airflow list_dags
# lists all default examples (load examples is set to false in compose)
```

Location of airflow is:
```
airflow@b64d95a03a95:~$ which airflow
/usr/local/bin/airflow
```

**It seems that in interactive mode `airflow` uses the default configuration and completely ignores the contents of compose. **

I also tried assigning another name to the psql service i.e. changed `postgres` to `scheduler-psql` and aliased it appropriately

```
    webserver:
    links:
      - scheduler-psql:postgres
```

In this case running `airflow trigger_dag tutorial` from inside the container complains that postgres service is not running even though the DAGs trigger and register correctly through the UI (and if I expose port 5432 I can access the db with a sql client).

Any ideas? I'm not sure where to go next debugging this. It would be great to have the flexibility of using CLI commands inside of the container.

Thanks!
