### ISSUE TITLE
CeleryExcutor please specify in format plugin_module.executor

### ISSUE THREAD

**Issue by moisesmorillo** [puckel/docker-airflow#228]
Docker compose fail to build services when CeleryExecutor is specified.

I have this output:

```airflow.exceptions.AirflowException: Executor airflow.executors.celery_executor - POSTGRES_USER=airflow - POSTGRES_PASSWORD=airflow - POSTGRES_DB=airflow - REDIS_PASSWORD=airflowExecutor not supported: please specify in format plugin_module.executor```

This is mi docker-compose.yml

```
version: '2.1'
services:
  redis:
    image: 'redis:3.2.7'
    command: redis-server --requirepass airflow

  postgres:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=airflow
    - POSTGRES_PASSWORD=airflow
    - POSTGRES_DB=airflow
    # Uncomment these lines to persist data on the local filesystem.
    #     - PGDATA=/var/lib/postgresql/data/pgdata
    # volumes:
    #     - ./pgdata:/var/lib/postgresql/data/pgdata

  webserver:
    image: puckel/docker-airflow:1.10.0-1
    restart: always
    depends_on:
    - postgres
    - redis
    environment:
    - LOAD_EX=n
    - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    - EXECUTOR=CeleryExecutor
    - POSTGRES_USER=airflow
    - POSTGRES_PASSWORD=airflow
    - POSTGRES_DB=airflow
    - REDIS_PASSWORD=airflow
    volumes:
    - ./dags:/usr/local/airflow/dags
    - ./requirements.txt:/requirements.txt
    # Uncomment to include custom plugins
    # - ./plugins:/usr/local/airflow/plugins
    ports:
    - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: puckel/docker-airflow:1.10.0-1
    restart: always
    depends_on:
    - redis
    ports:
    - "5555:5555"
    command: flower

  scheduler:
    image: puckel/docker-airflow:1.10.0-1
    restart: always
    depends_on:
    - webserver
    volumes:
    - ./dags:/usr/local/airflow/dags
    # Uncomment to include custom plugins
    # - ./plugins:/usr/local/airflow/plugins
    environment:
    - LOAD_EX=n
    - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    - EXECUTOR=CeleryExecutor
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - REDIS_PASSWORD=airflow
    command: scheduler

  worker:
    image: puckel/docker-airflow:1.10.0-1
    restart: always
    depends_on:
    - scheduler
    volumes:
    - ./dags:/usr/local/airflow/dags
    # Uncomment to include custom plugins
    # - ./plugins:/usr/local/airflow/plugins
    environment:
    - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    - EXECUTOR=CeleryExecutor
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - REDIS_PASSWORD=airflow
    command: worker
```
