### ISSUE TITLE
Defaults to no auth?

### ISSUE THREAD

**Issue by bicubic** [puckel/docker-airflow#264]
Using the following docker-compose configuration, I get an instance that spins up just fine but seems to accept logins without asking for any auth. An older deployment of the same configuration had to be authenticated to as the default user. My mistake or something changed?

```
version: '3'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  airflow:
    image: puckel/docker-airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./data:/data
    ports:
      - "8081:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
```
