### ISSUE TITLE
Install Extra Airflow Packages

### ISSUE THREAD

**Issue by yunus89** [puckel/docker-airflow#340]
How can i install extra airflow packages e.g `gcp_api` and `mysql` with `docker-compose` way (using `docker-compose-CeleryExecutor.yml`)

**Comment by ebunt** [comment]
Change the webserver service to begin with the following, or change to the version you are using.

```
webserver:
    image: puckel/docker-airflow:1.10.2
    build:
      context: https://github.com/puckel/docker-airflow.git#1.10.2
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: gcp_api,mysql        
```
