### ISSUE TITLE
Airflow Backfill Not Shown In WebUI Tree View

### ISSUE THREAD

**Issue by MaksimBocharenko** [puckel/docker-airflow#410]
Hello, 

I set up Airflow on EC2 instance with the yml file and commands at the bottom of question.

At the beginning I had only 4 tasks in my MyDAG with start_date 2019-02-01.
All historical tasks triggered (I think by scheduler) and marked dark green as expected after completed.

I added new (5th) task to MyDAG and tried to backfill as success all history for this task.

First I tried to use web ui where in tree view I tried to mark success future/past but it always marks single execution day only. (In opposite in my situation clear option works well and can clear all history of task)

Second I tried to backfill task with success by command:

```
sudo docker-compose exec webserver airflow backfill -t task_5 -s 2019-02-01 -e 2019-07-30 --mark_success MyDAG 
``` 
This command completed with success and this command
```
sudo docker-compose exec webserver airflow list_dag_runs MyDAG
```
listed all tasks as success as well.

The problem is that there are no changes in web ui tree view. All historical tasks cubes for task_5 are not colored. 

It feels like my docker-compose.yml missing something or web ui updates different db from shell command. As well web ui has some problem to mark past or future tasks status.

Any help will be appreciated.

Thanks.

Setup docker-compose.yml:

```
version: '3.6'

x-common-variables: &common-variables
  LOAD_EX: n
  FERNET_KEY: ___SOME_KEY___
  EXECUTOR: Celery
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: airflow
  POSTGRES_DB: airflow
  REDIS_PASSWORD: airflow
  RABBITMQ_DEFAULT_USER: airflow
  RABBITMQ_DEFAULT_PASS: airflow
  RABBITMQ_DEFAULT_VHOST: airflow

x-common-volumes: &common-volumes
  - ./dags:/usr/local/airflow/dags
  - ./plugins:/usr/local/airflow/plugins
  - ./requirements.txt:/requirements.txt
  - ./logs:/usr/local/airflow/logs
  - ./airflow.cfg:/usr/local/airflow/airflow.cfg

services:

  redis:
    image: 'redis:5.0.5'
    sysctls:
     - net.core.somaxconn=511
    command: redis-server --requirepass airflow
    ports:
        - "6379:6379"

  postgres:
    image: 'postgres:11.4'
    ports:
      - "5432:5432"
    environment:
      <<: *common-variables

  rabbitmq:
    image: 'rabbitmq:3.7.16-management'
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      <<: *common-variables

  webserver:
    image: puckel/docker-airflow:1.10.3
    restart: always
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      <<: *common-variables
    volumes:
      *common-volumes
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: puckel/docker-airflow:1.10.3
    restart: always
    depends_on:
      - redis
    environment:
      <<: *common-variables
    volumes:
      *common-volumes
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    image: puckel/docker-airflow:1.10.3
    restart: always
    depends_on:
      - webserver
    environment:
      <<: *common-variables
    volumes:
      *common-volumes
    command: scheduler

  worker:
    image: puckel/docker-airflow:1.10.3
    ports:
      - "8793:8793"  # airflow worker logs server
    restart: always
    depends_on:
      - scheduler
    environment:
      <<: *common-variables
    volumes:
      *common-volumes
    command: worker

``` 

Start Airflow commands:

```
sudo docker-compose up
sudo docker-compose exec webserver airflow upgradedb
```
