### ISSUE TITLE
Schduler not running when using SequentialExecutor.

### ISSUE THREAD

**Issue by sundios** [puckel/docker-airflow#422]
Hi,

Every time I run airflow using SequentialExecutor, my dag files are empty and there is a message that says: 'The scheduler does not appear to be running.

The DAGs list may not update, and new tasks will not be scheduled.'

Any idea why is this happening?

When I run airflow with LocalExecutor the scheduler works automatically, but there is no way to save files in the dag folder because it lives in usr/local/airflow/dags which I don't know where that is. 

Any help to clarify this?

**Comment by jtinsky** [comment]
I'm having the same issue. I'm new to both Airflow and Docker. I was able to confirm that /usr/local/airflow/dags does not exist by doing the following:

1. Get the id of the docker container by running `docker ps`

![image](https://user-images.githubusercontent.com/20485/62913356-9fea4d80-bd40-11e9-85d0-ad5e4e1e2017.png)

2. Then connect to the container in bash by running `docker exec -it <container id> bash`
3. Then list the directory to see what's in it with `ls -al /usr/local/airflow`

![image](https://user-images.githubusercontent.com/20485/62913290-5994ee80-bd40-11e9-9cef-8ba9cb8ec8a6.png)

I'm not sure if that's the clarification you're requesting or if you already know all that and it's redundant.

**Comment by jtinsky** [comment]
+1 on this issue

**Comment by realrnjs** [comment]
+1 on this issue

**Comment by enys** [comment]
Hi,

Could you list the command you used to start airflow? Are you using the provided docker-compose files ?

I'm guessing you have two distinct problems here. 
Using the LocalExectuor (and will run into the same problem with other modes), you need a bind mount.
If you look at the docker-compose files, you will see :+1: 
`
volumes:
            - ./dags:/usr/local/airflow/dags
`
This mounts your local 'dags' folder, from your current workdir, to /usr/local/airflow/dags, in the running container.

Any luck this works for you ?

**Comment by pedromachados** [comment]
Is this solved by this PR?

https://github.com/puckel/docker-airflow/pull/359

**Comment by sundios** [comment]
Hi,

It solves my issue of finding my dags folder. But Scheduler doesnt run with SequentialExecutor

**Comment by zhaobinnian** [comment]
i have the same problem,
"The scheduler does not appear to be running. Last heartbeat was received 54 minutes ago.The DAGs list may not update, and new tasks will not be scheduled."
are you solved it?

**Comment by ab-w** [comment]
Although PR #359 looks to have solved the issue, the fix is not a part of a tagged release yet. The fix doesn't exist in the most recent tagged release which is version 1.10.4.

What I did in the interim is created a `Dockerfile` as below:
```
# Upstream: https://github.com/puckel/docker-airflow/blob/1.10.4/Dockerfile
FROM puckel/docker-airflow:1.10.4

# For SequentialExecutor, apply relevant subset of https://github.com/puckel/docker-airflow/pull/359/files for airflow scheduler to run:
USER root
RUN sed -i 's/LocalExecutor/SequentialExecutor/' /entrypoint.sh
USER airflow

ENV EXECUTOR Sequential
HEALTHCHECK CMD "[ -f /usr/local/airflow/airflow-webserver.pid ]"
```

I then use the image created using this Dockerfile in my `docker-compose.yml`. The middle section of the above Dockerfile can presumably be removed after updating to 1.10.5.

**Comment by neverbeenthisweeb** [comment]
> Although PR #359 looks to have solved the issue, the fix is not a part of a tagged release yet. The fix doesn't exist in the most recent tagged release which is version 1.10.4.
> 
> What I did in the interim is created a `Dockerfile` as below:
> 
> ```
> # Upstream: https://github.com/puckel/docker-airflow/blob/1.10.4/Dockerfile
> FROM puckel/docker-airflow:1.10.4
> 
> # For SequentialExecutor, apply relevant subset of https://github.com/puckel/docker-airflow/pull/359/files for airflow scheduler to run:
> USER root
> RUN sed -i 's/LocalExecutor/SequentialExecutor/' /entrypoint.sh
> USER airflow
> 
> ENV EXECUTOR Sequential
> HEALTHCHECK CMD "[ -f /usr/local/airflow/airflow-webserver.pid ]"
> ```
> 
> I then use the image created using this Dockerfile in my `docker-compose.yml`. The middle section of the above Dockerfile can presumably be removed after updating to 1.10.5.

Hi, would u mind to share the docker-compose.yml? It looks like I did something wrong.

Here are my Dockerfile and docker-compose.yml

```
# Upstream: https://github.com/puckel/docker-airflow/blob/1.10.4/Dockerfile
FROM puckel/docker-airflow:1.10.4

# For SequentialExecutor, apply relevant subset of https://github.com/puckel/docker-airflow/pull/359/files for airflow scheduler to run:
USER root
RUN sed -i 's/LocalExecutor/SequentialExecutor/' /entrypoint.sh
USER airflow

ENV EXECUTOR Sequential
HEALTHCHECK CMD "[ -f /usr/local/airflow/airflow-webserver.pid ]"
```

```
version: '3'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build:
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=1PBwo32ccOspd6wpAkXkdU-YhPvIuc5qWqbdm4qr-Nk=
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
```
