### ISSUE TITLE
Dags not running and flower UI not working with Celery?

### ISSUE THREAD

**Issue by whillas** [puckel/docker-airflow#444]
Hello,

So everything seems fine, no errors in the logs, except that when i run a DAG it gets scheduled but none of the tasks start. I've just tried the `tutorial` and the `example_python_operatorschedule`. i.e. 
the flower web UI "Can't be reached". I've changed its port to "6666:5555" due to a conflict.

The flower logs look like this:
```[2019-10-07 04:35:40,509] {{settings.py:213}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=1
/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
[2019-10-07 04:35:40,790] {{__init__.py:51}} INFO - Using executor CeleryExecutor
[I 191007 04:35:41 command:136] Visit me at http://0.0.0.0:5555
[I 191007 04:35:41 command:141] Broker: redis://:**@redis:6379/1
[I 191007 04:35:41 command:144] Registered tasks: 
    ['celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap']
[I 191007 04:35:41 mixins:229] Connected to redis://:**@redis:6379/1
[W 191007 04:35:46 control:44] 'stats' inspect method failed
[W 191007 04:35:46 control:44] 'active_queues' inspect method failed
[W 191007 04:35:46 control:44] 'registered' inspect method failed
[W 191007 04:35:46 control:44] 'scheduled' inspect method failed
[W 191007 04:35:46 control:44] 'active' inspect method failed
[W 191007 04:35:46 control:44] 'reserved' inspect method failed
[W 191007 04:35:46 control:44] 'revoked' inspect method failed
[W 191007 04:35:46 control:44] 'conf' inspect method failed
```
All the other logs look normal. I'm in New Zealand and the server is on Auckland time, should that affect the scheduler?
The tail of the webserver logs looks like this:
```
[2019-10-07 04:57:06,089] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags
[2019-10-07 04:57:06 +0000] [29] [INFO] Handling signal: ttou
[2019-10-07 04:57:06 +0000] [544] [INFO] Worker exiting (pid: 544)
[2019-10-07 04:57:37 +0000] [29] [INFO] Handling signal: ttin
[2019-10-07 04:57:37 +0000] [609] [INFO] Booting worker with pid: 609
[2019-10-07 04:57:37,246] {{__init__.py:51}} INFO - Using executor CeleryExecutor
[2019-10-07 04:57:37,540] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags
[2019-10-07 04:57:38 +0000] [29] [INFO] Handling signal: ttou
[2019-10-07 04:57:38 +0000] [557] [INFO] Worker exiting (pid: 557)
[2019-10-07 04:58:08 +0000] [29] [INFO] Handling signal: ttin
[2019-10-07 04:58:08 +0000] [622] [INFO] Booting worker with pid: 622
[2019-10-07 04:58:08,675] {{__init__.py:51}} INFO - Using executor CeleryExecutor
[2019-10-07 04:58:08,971] {{dagbag.py:90}} INFO - Filling up the DagBag from /usr/local/airflow/dags
[2019-10-07 04:58:09 +0000] [29] [INFO] Handling signal: ttou
[2019-10-07 04:58:09 +0000] [570] [INFO] Worker exiting (pid: 570)
```
which seems to happen when i run a DAG.

Finally, the only changes made to the `docker-compose-CeleryExecutor.yml` are removing some comments and changing the flower port:
```yaml
version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        # Uncomment these lines to persist data on the local filesystem.
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata

    webserver:
        image: puckel/docker-airflow:1.10.4
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "9090:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: puckel/docker-airflow:1.10.4
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_PASSWORD=redispass
        ports:
            - "6666:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow:1.10.4
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=y
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        image: puckel/docker-airflow:1.10.4
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
        command: worker
```
I created the `/var/lib/postgresql/data/pgdata` dir and `chmod 777`ed it. There doesn't seem to be anything in there?

No sure how to debug this :?

p.s. is there an example with RabbitMQ instead of redis?
