### ISSUE TITLE
How to to run jobs on docker-airflow ?

### ISSUE THREAD

**Issue by kzarzycki** [puckel/docker-airflow#5]
Hi there! 
I've installed your docker-airflow images and they run examples fine (except http requests, but it's for another ticket).
Now I would like to run my own DAG, could you please explain how to do it with your images?
a) can/should I use running containers to launch DAGs?
b) can/should I rather install airflow distribution, configure & use that as a client?

I think it is valuable information to others, could you please write the instructions in your README? 

Thanks!
Krzysiek

**Comment by puckel** [comment]
Hi,

Did you try to use a volume containing your DAGs ? 

In the docker-compose.yml file, add a volumes definition :
```
webserver:
    container_name: webserver
    image: puckel/docker-airflow
    restart: always
    volumes:
        - /local/path/to/dags:/usr/local/airflow/dags
...
```
Puckel.
