### ISSUE TITLE
Airflow running on GCP Compute Engine getting tagged for Cryptomining when no Cryptomining is happening.

### ISSUE THREAD

**Issue by guyandtheworld** [puckel/docker-airflow#507]
I receive this email and my VM instance gets suspended. It is an airflow server that runs multiple processes. The instance is mostly used for some ML preprocessing, writing and making predictions and storing it into the CloudSQL. I receive this particular email after 24 hours of running and my VM gets suspended and this issue only happens on the airflow VM and not any of the other VMs which are running. The weird thing I noticed is that the celery docker-compose works at 100% in a 2 CPU, 10 GB Ram Compute Instance. Is that normal or is some kind of memory leakage happening which? 

This is the email I received

Dear Developer,
We've detected that your Google Cloud Project is engaging in cryptocurrency mining, resulting in the suspension of all project resources displaying this behavior.

I tried posting this on GCP support and Stackoverflow and it has been largely futile. But I received this email
```
This is the exact update that we received from the Trust and Safety team.

"The resources associated with your project are being suspended for cryptocurrency mining in violation of our Terms of Service.

    abuse_start_timestamp: "2020-02-17 16:17"
    abuse_stop_timestamp: "2020-02-17 16:25"
    source_ips: "34.87.94.235"
    destination_ips: "107.173.160.165"
    urls: "107.173.160.165"
    total_core_hours: 101.0
    vm_resource_id_zone_name: "2080774995510078591:asia-southeast1-b"
    vm_hostname_zone_name: "airflow:asia-southeast1-b"
    remote_port_list: "5555"
```

I'm running all of the containers including postgres in one n1 compute engine instance using `docker-compose up` since we're just testing stuff out. This is the docker-compose and Dockerfile for the instance respectively. 

docker-compose
```
version: '2.1'
services:
    redis:
        image: 'redis:5.0.5'
        # command: redis-server --requirepass redispass
        ports:
            - "6379:6379"

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./.pgdata:/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"

    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        env_file:
          - .keys/airflow.env

    flower:
        build: .
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build: .
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler
        env_file:
          - .keys/airflow.env

    worker:
        build: .
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_HOST=35.246.27.83
            # - REDIS_HOST=35.246.27.83
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker
        env_file:
          - .keys/airflow.env
```

Dockerfile
```
# VERSION 1.10.7
# AUTHOR: Matthieu "Puckel_" Roisil
# DESCRIPTION: Basic Airflow container
# BUILD: docker build --rm -t puckel/docker-airflow .
# SOURCE: https://github.com/puckel/docker-airflow

FROM python:3.7-slim-stretch
LABEL maintainer="Puckel_"

# Never prompt the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND noninteractive
ENV TERM linux

# Airflow
ARG AIRFLOW_VERSION=1.10.8
ARG AIRFLOW_USER_HOME=/usr/local/airflow
ARG AIRFLOW_DEPS=""
ARG PYTHON_DEPS=""
ENV AIRFLOW_HOME=${AIRFLOW_USER_HOME}

# Define en_US.
ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
ENV LC_MESSAGES en_US.UTF-8

# Disable noisy "Handling signal" log messages:
# ENV GUNICORN_CMD_ARGS --log-level WARNING

RUN set -ex \
    && buildDeps=' \
    freetds-dev \
    libkrb5-dev \
    libsasl2-dev \
    libssl-dev \
    libffi-dev \
    libpq-dev \
    git \
    ' \
    && apt-get update -yqq \
    && apt-get upgrade -yqq \
    && apt-get install -yqq --no-install-recommends \
    $buildDeps \
    freetds-bin \
    build-essential \
    default-libmysqlclient-dev \
    apt-utils \
    build-essential \
    curl \
    rsync \
    netcat \
    libssl-dev \
    libffi-dev \
    libxml2-dev \
    libxslt1-dev \
    locales \
    python-dev \
    python3-dev \
    wget \
    zlib1g-dev \
    && sed -i 's/^# en_US.UTF-8 UTF-8$/en_US.UTF-8 UTF-8/g' /etc/locale.gen \
    && locale-gen \
    && update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 \
    && useradd -ms /bin/bash -d ${AIRFLOW_USER_HOME} airflow \
    && pip install -U pip setuptools wheel \
    && pip install pytz \
    && pip install pyOpenSSL \
    && pip install ndg-httpsclient \
    && pip install pyasn1 \
    && pip install 'werkzeug<1.0.0' \
    && pip install apache-airflow[crypto,celery,postgres,hive,jdbc,mysql,ssh${AIRFLOW_DEPS:+,}${AIRFLOW_DEPS}]==${AIRFLOW_VERSION} \
    && pip install lxml Cython psycopg2-binary \
    && pip install 'redis==3.2' \
    && if [ -n "${PYTHON_DEPS}" ]; then pip install ${PYTHON_DEPS}; fi \
    && apt-get purge --auto-remove -yqq $buildDeps \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/* \
    /usr/share/man \
    /usr/share/doc \
    /usr/share/doc-base

COPY requirements.txt ${AIRFLOW_USER_HOME}/requirements.txt
RUN pip install -r ${AIRFLOW_USER_HOME}/requirements.txt

RUN wget https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz
RUN pip install en_core_web_sm-2.2.0.tar.gz
RUN rm en_core_web_sm-2.2.0.tar.gz

COPY script/entrypoint.sh /entrypoint.sh

RUN touch __init__.py

COPY config/airflow.cfg ${AIRFLOW_USER_HOME}/airflow.cfg
COPY utils ${AIRFLOW_USER_HOME}/utils
COPY .keys ${AIRFLOW_USER_HOME}/.keys

RUN chown -R airflow: ${AIRFLOW_USER_HOME}

EXPOSE 8080 5555 8793

USER airflow
WORKDIR ${AIRFLOW_USER_HOME}
ENTRYPOINT ["/entrypoint.sh"]
CMD ["webserver"]
```

Any help is appreciated.
