### ISSUE TITLE
Easy way of creating a new admin user

### ISSUE THREAD

**Issue by dinigo** [puckel/docker-airflow#515]
It would be great to have another command in the entrypoint to create a default admin user on deploy, right after de `initdb`. Something like the following:

```python
from airflow import models, settings
from airflow.contrib.auth.backends.password_auth import PasswordUser
from sqlalchemy import create_engine
from os import getenv

POSTGRES_USER = getenv('POSTGRES_USER')
POSTGRES_PASSWORD = getenv('POSTGRES_PASSWORD')
POSTGRES_DB = getenv('POSTGRES_DB')

ADMIN_USER = getenv('ADMIN_USER')
ADMIN_PASSWORD = getenv('ADMIN_PASSWORD')
ADMIN_EMAIL = getenv('ADMIN_EMAIL')

if None not in (ADMIN_EMAIL, ADMIN_PASSWORD, ADMIN_USER):
    user = PasswordUser(models.User())
    user.username = ADMIN_USER
    user.email = ADMIN_EMAIL
    user.password = ADMIN_PASSWORD
    engine = create_engine(f'postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@postgres:5432/{POSTGRES_DB}')
    session = settings.Session(bind=engine)
    session.add(user)
    session.commit()
    session.close()
```

So that if I run have a docker stack/compose configuration file like the following it will create the user at provision time:
```yaml
version: '3.3'
services:
    webserver:
        image: puckel/docker-airflow
        environment:
            - ADMIN_USER=frank
            - ADMIN_PASSWORD=frankistheboss
            - ADMIN_EMAIL=frank@frakly.com
```

Are you open to PRs? I can modify this for my company, but I would rather see it merged for the rest of the people if they find it usefull
