### ISSUE TITLE
Connecting to other DB instance from worker not possible

### ISSUE THREAD

**Issue by ptrhck** [puckel/docker-airflow#527]
Hi everyone,

I am using the provided docker-compose file to run airflow. In addition, I am having another db instance to which some python scripts should connect to using dags. Adding a network to establish a connection between the worker and the other db instance results in the worker container to something like: `Waiting for Postgres ....`. It is not finding the ariflow postgres db instance anymore, even though the hostname is defined.

So the goal is to run two postgres instances, the default one for airflow and another instace which I connect to from the worker through dags using the host `db `and port `5432`.

Here is the docker-compose file I am using:

```
version: '2.1'
services:
  redis:
    image: 'redis:5.0.5'
    # command: redis-server --requirepass redispass


  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=fdajkfd
      - POSTGRES_DB=db
    networks:
      - db_airflow_nw
    restart: always

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    # Uncomment these lines to persist data on the local filesystem.
    #     - PGDATA=/var/lib/postgresql/data/pgdata
    # volumes:
    #     - ./pgdata:/var/lib/postgresql/data/pgdata

  webserver:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      # - POSTGRES_USER=airflow
      # - POSTGRES_PASSWORD=airflow
      # - POSTGRES_DB=airflow
      # - REDIS_PASSWORD=redispass
    volumes:
      - ./dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
      # - REDIS_PASSWORD=redispass
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      # - POSTGRES_USER=airflow
      # - POSTGRES_PASSWORD=airflow
      # - POSTGRES_DB=airflow
      # - REDIS_PASSWORD=redispass
    command: scheduler

  worker:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      # - POSTGRES_USER=airflow
      # - POSTGRES_PASSWORD=airflow
      # - POSTGRES_DB=airflow
      # - REDIS_PASSWORD=redispass
    networks:
      - db_airflow_nw
    command: worker

networks:
  db_airflow_nw:
    driver: bridge
```

Any idea why the worker cannot find the airflow db instance anymore?
