### ISSUE TITLE
password authentication failed for user 'airflow'

### ISSUE THREAD

**Issue by thucnc** [puckel/docker-airflow#69]
As I already have redis and postgres containers in my server, so I rewrote the docker-compose as below:

```
version: '2'
services:
    webserver:
        image: puckel/docker-airflow:latest
        restart: always
        network_mode: bridge
        external_links: 
            - bi-postgres:postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - /root/notebooks/dags:/usr/local/airflow/dags
        ports:
            - "5002:8080"
        command: webserver

    flower:
        image: puckel/docker-airflow:latest
        restart: always
        network_mode: bridge
        external_links:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - webserver
        volumes:
            - /root/notebooks/dags:/usr/local/airflow/dags
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: scheduler -n 5

    worker:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - scheduler
        volumes:
            - /root/notebooks/dags:/usr/local/airflow/dags
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: worker
```
And I got issue on running initdb (DB: postgresql+psycopg2://airflow:***@postgres/airflow), but the redis get connected well. Please help.
