### ISSUE TITLE
Running on Kubernetes

### ISSUE THREAD

**Issue by tomazzaman** [puckel/docker-airflow#91]
This is actually not an issue, just a few gotchas I've encountered when installing this image on Kubernetes that I'd like to share with anyone trying to accomplish the same thing.

The problem with the image is that on every run, it will try to update the `airflow.cfg`, which I would recommend not to (because it will most likely break). Instead, open the original file and manually edit the details, then create a GlusterFS cluster with an `airflow` volume (and the `cfg` file inside), then mount it onto pods under `/usr/local/airflow`.

Another issue I stumbled upon is that workers and webserver prefer to be on the same logical host, which is not an issue, we can just schedule multiple containers in the same pod.

The final issue is the `entrypoint.sh` because, as I've written above, it tries to configure our stack _every_ time. To avoid this, we can set our own `command` in the pod configuration, like this:

```yaml
# this is inside "containers" key in pod definition
  - command:
    - /bin/bash
    - -ec
    - |
      $(which pip) install --user -r /usr/local/airflow/requirements.txt
      exec airflow worker
```

So here are the two `yaml` files I'm using to successfully run our stack, based on this image.

The main deployment that runs three pods, webserver, worker and scheduler:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: airflow
  name: airflow
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: airflow
    spec:
      containers:
      - command:
        - /bin/bash
        - -ec
        - |
          $(which pip) install --user -r /usr/local/airflow/requirements.txt
          exec airflow webserver
        env:
        - name: LOAD_EX
          value: "y"
        - name: AIRFLOW_HOME
          value: /usr/local/airflow
        image: puckel/docker-airflow:1.8.1
        imagePullPolicy: Always
        name: airflow
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/airflow
          name: glusterfs
      - command:
        - /bin/bash
        - -ec
        - |
          $(which pip) install --user -r /usr/local/airflow/requirements.txt
          exec airflow scheduler
        env:
        - name: LOAD_EX
          value: "y"
        - name: AIRFLOW_HOME
          value: /usr/local/airflow
        image: puckel/docker-airflow:1.8.1
        imagePullPolicy: Always
        name: scheduler
        volumeMounts:
        - mountPath: /usr/local/airflow
          name: glusterfs
      - command:
        - /bin/bash
        - -ec
        - |
          $(which pip) install --user -r /usr/local/airflow/requirements.txt
          exec airflow worker
        env:
        - name: LOAD_EX
          value: "y"
        - name: AIRFLOW_HOME
          value: /usr/local/airflow
        image: puckel/docker-airflow:1.8.1
        imagePullPolicy: Always
        name: worker
        ports:
        - containerPort: 8793
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/airflow
          name: glusterfs      
      restartPolicy: Always
      volumes:
      - glusterfs:
          endpoints: glusterfs
          path: /airflow
        name: glusterfs

```

And the (optional) flower deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: flower
  name: flower
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - command:
        - /bin/bash
        - -ec
        - |
          $(which pip) install --user -r /usr/local/airflow/requirements.txt
          exec airflow flower
        env:
        - name: AIRFLOW_HOME
          value: /usr/local/airflow
        - name: FLOWER_PORT
          value: "5555"
        image: puckel/docker-airflow:1.8.1
        imagePullPolicy: Always
        name: flower
        ports:
        - containerPort: 5555
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/airflow
          name: glusterfs
      volumes:
      - glusterfs:
          endpoints: glusterfs
          path: /airflow
        name: glusterfs

```
